# Generated by Django 5.2.7 on 2026-10-02 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=40, verbose_name='Plateforme')),
                ('external_id', models.CharField(blank=True, max_length=120, verbose_name='Identifiant chez la plateforme')),
                ('file', models.FileField(upload_to='factures-recues/%Y/', verbose_name='Fichier reçu')),
                ('file_sha256', models.CharField(max_length=64, unique=True)),
                ('flavor', models.CharField(blank=True, max_length=30, verbose_name='Format')),
                ('is_credit_note', models.BooleanField(default=False, verbose_name='Avoir')),
                ('number', models.CharField(max_length=60, verbose_name='Numéro')),
                ('issue_date', models.DateField(verbose_name='Date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Échéance')),
                ('seller_name', models.CharField(max_length=200, verbose_name='Fournisseur')),
                ('seller_siren', models.CharField(blank=True, max_length=20, verbose_name='SIREN du fournisseur')),
                ('seller_vat_number', models.CharField(blank=True, max_length=30, verbose_name='N° de TVA du fournisseur')),
                ('buyer_siren', models.CharField(blank=True, max_length=20, verbose_name="SIREN de l'acheteur")),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Devise')),
                ('total_ht', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total HT')),
                ('total_vat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total TVA')),
                ('total_ttc', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total TTC')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Reste à payer')),
                ('vat_breakdown', models.JSONField(default=list, verbose_name='TVA par taux')),
                ('lines', models.JSONField(default=list, verbose_name='Lignes')),
                ('data', models.JSONField(default=dict, verbose_name='Données de la facture (EN 16931)')),
                ('status', models.PositiveIntegerField(default=203, verbose_name='Statut')),
                ('status_reason', models.CharField(blank=True, max_length=300, verbose_name='Motif')),
                ('expense_account', models.CharField(blank=True, help_text="Vide : compte d'achat par défaut de la comptabilité.", max_length=20, verbose_name='Compte de charge')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Facture reçue',
                'verbose_name_plural': 'Factures reçues',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='invoicingsettings',
            name='ereporting_period',
            field=models.CharField(choices=[('decade', 'Par décade (régime réel normal mensuel)'), ('month', 'Par mois'), ('bimonth', 'Tous les deux mois (régime simplifié)')], default='decade', max_length=10, verbose_name='Période du e-reporting'),
        ),
        migrations.AddField(
            model_name='invoicingsettings',
            name='platform',
            field=models.CharField(default='manual', help_text='Plateforme qui transmet les factures électroniques, reçoit celles des fournisseurs et le e-reporting. « Dépôt manuel » : fichiers à déposer soi-même sur le portail de la plateforme.', max_length=40, verbose_name='Plateforme agréée'),
        ),
        migrations.CreateModel(
            name='EReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Du')),
                ('period_end', models.DateField(verbose_name='Au')),
                ('rows', models.JSONField(default=list, verbose_name='Données')),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total HT')),
                ('total_vat', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total TVA')),
                ('platform', models.CharField(max_length=40, verbose_name='Plateforme')),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('transmitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Transmis le')),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'E-reporting',
                'verbose_name_plural': 'E-reporting',
                'ordering': ['-period_start'],
                'constraints': [models.UniqueConstraint(fields=('period_start', 'period_end'), name='unique_ereport_period')],
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=40, verbose_name='Plateforme')),
                ('external_id', models.CharField(blank=True, max_length=120, verbose_name='Identifiant chez la plateforme')),
                ('status', models.PositiveIntegerField(blank=True, null=True, verbose_name='Statut')),
                ('error', models.TextField(blank=True, verbose_name='Dernière erreur')),
                ('payment_reported', models.BooleanField(default=False, verbose_name='Encaissement transmis')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transmission', to='invoicing.invoice')),
            ],
            options={
                'verbose_name': 'Transmission',
                'verbose_name_plural': 'Transmissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(verbose_name='Statut')),
                ('message', models.CharField(blank=True, max_length=300, verbose_name='Précision')),
                ('source', models.CharField(blank=True, help_text='plateforme, utilisateur…', max_length=40, verbose_name='Origine')),
                ('sent', models.BooleanField(default=False, verbose_name='Transmis à la plateforme')),
                ('at', models.DateTimeField(verbose_name='Date')),
                ('incoming', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='invoicing.incominginvoice')),
                ('transmission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='invoicing.transmission')),
            ],
            options={
                'ordering': ['at', 'pk'],
            },
        ),
    ]
