# Generated by Django 5.2.7 on 2026-10-02 11:32

import django.db.models.deletion
from django.db import migrations, models


def fill_defaults(apps, schema_editor):
    """Comptes par défaut des achats pour les installations existantes (créés s'ils manquent)."""
    Account = apps.get_model("accounting", "Account")
    AccountingSettings = apps.get_model("accounting", "AccountingSettings")
    defaults = {"supplier_account": ("401000", "Fournisseurs", "liability"),
                "purchases_account": ("607000", "Achats de marchandises", "expense"),
                "deductible_vat_account": ("445660", "TVA déductible sur autres biens et services", "asset")}
    for settings in AccountingSettings.objects.all():
        for field, (code, name, kind) in defaults.items():
            if getattr(settings, f"{field}_id") is None:
                account, _ = Account.objects.get_or_create(code=code, defaults={"name": name, "account_type": kind})
                setattr(settings, field, account)
        settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_payment_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='deductible_vat_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account', verbose_name='TVA déductible'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='purchases_account',
            field=models.ForeignKey(blank=True, help_text='Charge des factures fournisseurs reçues, modifiable écriture par écriture.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account', verbose_name='Achats (compte par défaut)'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='supplier_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account', verbose_name='Fournisseurs'),
        ),
        migrations.RunPython(fill_defaults, migrations.RunPython.noop),
    ]
