# Generated by Django 5.2.7 on 2026-10-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_vat_on_receipts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SealAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveBigIntegerField(verbose_name='Maillon')),
                ('seal', models.CharField(max_length=64, verbose_name='Sceau')),
                ('reason', models.CharField(default='quotidien', max_length=60, verbose_name='Motif')),
                ('channel', models.CharField(choices=[('email', 'E-mail'), ('file', "Fichier d'archive")], max_length=10, verbose_name='Canal')),
                ('destination', models.CharField(max_length=500, verbose_name='Destinataires ou fichier')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Envoi de sceau',
                'verbose_name_plural': 'Envois de sceaux',
                'ordering': ('-sent_at', '-pk'),
            },
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='seal_recipients',
            field=models.TextField(blank=True, help_text='Adresses e-mail (une par ligne ou séparées par des virgules) qui reçoivent chaque jour le sceau de la chaîne des écritures et le sceau de chaque clôture : expert-comptable, dirigeant. À conserver.', verbose_name='Destinataires des sceaux'),
        ),
    ]
