# Generated by Django 5.2.7 on 2026-10-02 10:56

import django.db.models.deletion
import invoicing.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(blank=True, max_length=160, verbose_name='Raison sociale')),
                ('seller_legal_form', models.CharField(blank=True, help_text='SAS, SARL, EI…', max_length=60, verbose_name='Forme juridique')),
                ('seller_capital', models.CharField(blank=True, max_length=40, verbose_name='Capital social')),
                ('seller_address', models.CharField(blank=True, max_length=200, verbose_name='Adresse')),
                ('seller_postal_code', models.CharField(blank=True, max_length=12, verbose_name='Code postal')),
                ('seller_city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('seller_country', models.CharField(default='FR', max_length=2, verbose_name='Pays (code ISO)')),
                ('seller_siren', models.CharField(blank=True, max_length=9, verbose_name='SIREN')),
                ('seller_siret', models.CharField(blank=True, max_length=14, verbose_name='SIRET')),
                ('seller_vat_number', models.CharField(blank=True, max_length=20, verbose_name='N° de TVA intracommunautaire')),
                ('seller_rcs', models.CharField(blank=True, max_length=80, verbose_name='RCS / RM')),
                ('seller_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('seller_phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('seller_iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN (paiement par virement)')),
                ('invoice_prefix', models.CharField(default='F', max_length=10, verbose_name='Préfixe des factures')),
                ('credit_note_prefix', models.CharField(default='AV', max_length=10, verbose_name='Préfixe des avoirs')),
                ('operation_category', models.CharField(choices=[('goods', 'Livraisons de biens'), ('services', 'Prestations de services'), ('both', 'Biens et services')], default='goods', help_text='Mention obligatoire des factures électroniques.', max_length=20, verbose_name='Nature des opérations')),
                ('vat_on_debits', models.BooleanField(default=False, verbose_name="Option pour le paiement de la TVA d'après les débits")),
                ('vat_exemption', models.CharField(blank=True, help_text='Ex. : « TVA non applicable, art. 293 B du CGI » (franchise en base). Imprimée si la TVA est nulle.', max_length=200, verbose_name="Mention d'exonération de TVA")),
                ('late_penalties', models.TextField(blank=True, default="En cas de retard de paiement, pénalités au taux de trois fois le taux d'intérêt légal (art. L441-10 du code de commerce).", help_text="Imprimées pour les clients professionnels, avec l'indemnité forfaitaire de 40 € et l'absence d'escompte.", verbose_name='Pénalités de retard (clients professionnels)')),
                ('footer', models.TextField(blank=True, verbose_name='Pied de page')),
            ],
            options={
                'verbose_name': 'Paramètres de facturation',
                'verbose_name_plural': 'Paramètres de facturation',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Identifiant de l'événement source (idempotence).", max_length=120, unique=True, verbose_name='Clé')),
                ('kind', models.CharField(choices=[('invoice', 'Facture'), ('credit_note', 'Avoir')], default='invoice', max_length=20, verbose_name='Type')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='Numéro')),
                ('issue_date', models.DateField(verbose_name="Date d'émission")),
                ('sale_date', models.DateField(blank=True, null=True, verbose_name='Date de la vente ou de la livraison')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Échéance')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Devise')),
                ('seller', models.JSONField(default=dict, verbose_name="Vendeur (à la date d'émission)")),
                ('buyer_name', models.CharField(max_length=160, verbose_name='Client')),
                ('buyer_address', models.CharField(blank=True, max_length=200, verbose_name='Adresse')),
                ('buyer_postal_code', models.CharField(blank=True, max_length=12, verbose_name='Code postal')),
                ('buyer_city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('buyer_country', models.CharField(default='FR', max_length=2, verbose_name='Pays')),
                ('buyer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('buyer_siren', models.CharField(blank=True, max_length=9, verbose_name='SIREN du client')),
                ('buyer_vat_number', models.CharField(blank=True, max_length=20, verbose_name='N° de TVA du client')),
                ('buyer_reference', models.CharField(blank=True, max_length=60, verbose_name='Référence client / commande')),
                ('delivery_address', models.CharField(blank=True, help_text="Si elle diffère de l'adresse de facturation.", max_length=300, verbose_name='Adresse de livraison')),
                ('prices_include_tax', models.BooleanField(default=True, verbose_name='Prix saisis TTC')),
                ('lines_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Total des lignes HT')),
                ('allowances', models.JSONField(blank=True, default=list, verbose_name='Remises')),
                ('allowances_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Remises HT')),
                ('vat_breakdown', models.JSONField(default=list, verbose_name='TVA par taux')),
                ('total_ht', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total HT')),
                ('total_vat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total TVA')),
                ('total_ttc', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total TTC')),
                ('payment_terms', models.CharField(blank=True, max_length=200, verbose_name='Conditions de paiement')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='Acquittée le')),
                ('payment_method', models.CharField(blank=True, max_length=60, verbose_name='Moyen de paiement')),
                ('note', models.TextField(blank=True, verbose_name='Mention')),
                ('document_type', models.CharField(blank=True, max_length=40, verbose_name='Type de pièce source')),
                ('document_id', models.CharField(blank=True, max_length=64, verbose_name='Identifiant de la pièce source')),
                ('pdf', models.FileField(blank=True, upload_to='factures/%Y/', verbose_name='PDF Factur-X')),
                ('pdf_sha256', models.CharField(blank=True, max_length=64, verbose_name='Empreinte SHA-256 du PDF')),
                ('public_token', models.CharField(default=invoicing.models.new_token, editable=False, max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credited_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='invoicing.invoice', verbose_name='Facture annulée')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-issue_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=300, verbose_name='Désignation')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité')),
                ('unit', models.CharField(default='C62', max_length=3, verbose_name='Unité')),
                ('net_price', models.DecimalField(decimal_places=6, max_digits=14, verbose_name='Prix unitaire HT')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant HT')),
                ('vat_rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Taux de TVA')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.invoice')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('prefix', 'year'), name='unique_invoice_sequence')],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['document_type', 'document_id'], name='invoicing_i_documen_51795f_idx'),
        ),
    ]
