# Generated by Django 5.2.7 on 2026-10-02 15:13

from django.db import migrations


def add_gap_accounts(apps, schema_editor):
    """Comptes des écarts de règlement soldés au lettrage (installations existantes)."""
    Account = apps.get_model("accounting", "Account")
    for code, name, kind in [("658000", "Charges diverses de gestion courante", "expense"),
                             ("758000", "Produits divers de gestion courante", "revenue")]:
        Account.objects.get_or_create(code=code, defaults={"name": name, "account_type": kind})


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_purchase_accounts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-date', '-id'), 'permissions': [('close_period', 'Peut clôturer un exercice'), ('view_reports', 'Peut consulter les rapports comptables'), ('export_data', 'Peut exporter les données comptables'), ('validate_transaction', 'Peut valider une écriture'), ('reconcile_entries', 'Peut lettrer les comptes de tiers')], 'verbose_name': 'Écriture', 'verbose_name_plural': 'Écritures'},
        ),
        migrations.RunPython(add_gap_accounts, migrations.RunPython.noop),
    ]
