# Generated by Django 5.2.7 on 2026-10-02 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_reconcile_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-date', '-id'), 'permissions': [('close_period', 'Peut clôturer un exercice'), ('view_reports', 'Peut consulter les rapports comptables'), ('export_data', 'Peut exporter les données comptables'), ('validate_transaction', 'Peut valider une écriture'), ('reconcile_entries', 'Peut lettrer les comptes de tiers'), ('reconcile_bank', 'Peut importer les relevés et rapprocher les comptes bancaires')], 'verbose_name': 'Écriture', 'verbose_name_plural': 'Écritures'},
        ),
        migrations.CreateModel(
            name='BankMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('auto', 'Automatique'), ('manual', 'Manuel'), ('entry', 'Écriture créée'), ('prior', 'Antérieure au premier relevé')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pointage bancaire',
                'verbose_name_plural': 'Pointages bancaires',
            },
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='bank_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='accounting.bankmatch', verbose_name='Pointage'),
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Fichier')),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('ofx', 'OFX'), ('camt053', 'CAMT.053 (ISO 20022)'), ('cfonb120', 'CFONB 120')], max_length=20, verbose_name='Format')),
                ('file_sha256', models.CharField(max_length=64)),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Du')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Au')),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Solde initial')),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Solde final')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_statements', to='accounting.account', verbose_name='Compte de banque')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relevé bancaire',
                'verbose_name_plural': 'Relevés bancaires',
                'ordering': ('-date_end', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='BankLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='Date de valeur')),
                ('label', models.CharField(max_length=255, verbose_name='Libellé')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='Référence')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant')),
                ('fingerprint', models.CharField(max_length=64)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_lines', to='accounting.account')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='accounting.bankmatch')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.bankstatement')),
            ],
            options={
                'verbose_name': 'Opération bancaire',
                'verbose_name_plural': 'Opérations bancaires',
                'ordering': ('date', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='bankstatement',
            constraint=models.UniqueConstraint(fields=('account', 'file_sha256'), name='unique_bank_statement_file'),
        ),
        migrations.AddConstraint(
            model_name='bankline',
            constraint=models.UniqueConstraint(fields=('account', 'fingerprint'), name='unique_bank_line'),
        ),
    ]
